### ISSUE TITLE
Cannot build asteroids

### ISSUE THREAD

**Issue by FranklinChen** [ocharles/netwire-classics#8]
I tried building asteroids with GHC 7.8.3, with Cabal sandbox, and failed. I suppose the whole repo should indicate what versions of GHC it can build with.

```
[14 of 16] Compiling Graphics.UI.SDL.Events ( dist/dist-sandbox-39727611/build/Graphics/UI/SDL/Events.hs, dist/dist-sandbox-39727611/build/Graphics/UI/SDL/Events.o )

Graphics/UI/SDL/Events.hsc:56:23:
    Module ‘Data.Typeable’ does not export ‘Typeable(typeOf)’
```

**Comment by ocharles** [comment]
I am no longer working on this repository, so I will have to close this issue. If any one fixes it, a PR is welcome.
