### ISSUE TITLE
building netwire-classics

### ISSUE THREAD

**Issue by ynimous** [ocharles/netwire-classics#9]
I'm sure I'm missing something trivial, but I'm not sure how to build this.

I tried using nix, but I get:

```
$ nix-shell
error: attribute ‘cabal’ missing, at /src/netwire-classics/default.nix:4:4

$ nix-env -q
cabal-install-1.22.6.0
cabal2nix-20150922
ghc-7.10.2
nix-1.10
```

**Comment by ocharles** [comment]
Unfortunately the packaging for this repository has bit-rotted now. You'll either need a much older version of `nixpkgs` (from the time I worked on this), or will need to patch `shell.nix`. You might have more luck using `stack` or something instead. I have finished work on this for now though, and will only be able to help with merging pull requests - I won't be making further changes.
